version: '2'

volumes:
  datamongo: {}

services:


##
# Access Mamaner
##
  nginx:
    image: nginx:1.16-alpine
    container_name: gio_am_nginx
    restart: always
    volumes:
      - /api/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      
  am-mongodb:
    image: mongo:3.4
    container_name: gio_am_mongodb
    restart: always
    volumes:
      - /api/mongo_am/data:/data/db

  am-gateway_am:
    image: graviteeio/am-gateway:2
    container_name: gio_am_gateway
    restart: always
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb_am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://mongodb_am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000

  am-management_am:
    image: graviteeio/am-management-api:2
    container_name: gio_am_management
    restart: always
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb_am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://mongodb_am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000

  am-webui_am:
    image: graviteeio/am-management-ui:2
    container_name: gio_am_webui
    restart: always
    environment:
      - MGMT_API_URL=http://10.1.7.104:80/am
      - MGMT_UI_URL=http://10.1.7.104:80/am/ui

    image: graviteeio/am-management-ui:2
    container_name: gio_am_webui
    restart: always
    environment:
      - MGMT_API_URL=http://10.1.7.104:${NGINX_PORT}/am
      - MGMT_UI_URL=http://10.1.7.104:${NGINX_PORT}/am/ui