version: '3'

services:

  mysql:
      image: mysql:5.7
      networks:
          - api_net
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      volumes:
        - /api/mysql/data:/var/lib/mysql
      deploy:
          resources:
              limits:
                  memory: 700M
          restart_policy:
              condition: on-failure
          placement:
              constraints:
                  - "node.platform.os == linux"

  keycloak:
      image: jboss/keycloak:3.2.0.Final
      networks:
          - api_net
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      ports:
        - 8081:8080
        - 9990:9990
      deploy:
          resources:
              limits:
                  memory: 200M
          restart_policy:
              condition: on-failure
          placement:
              constraints:
                  - "node.platform.os == linux"

networks:
    api_net:
        external: true