FROM graviteeio/management-ui:latest

COPY pt-BR.json /var/www/html/portal/i18n/pt-BR.json
COPY custom-theme.json /var/www/html/themes/custom-theme.json
COPY gravitee.css /var/www/html/themes/assets/ms.css
COPY GRAVITEE_LOGO1-01.png /var/www/html/themes/assets/MS_LOGO1-01.png